version: '3.7'
services:
  wordpress:
    container_name: mon-wordpress
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - /mnt/docker/wordpress:/var/www/html
      - /mnt/docker/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - app-tier
      - db-tier
  db:
    container_name: mon-mariadb
    image: mariadb
    volumes:
      - /mnt/docker/mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - db-tier
  nginx-proxy-manager:
    container_name: nginx_proxy_manager
    image: jc21/nginx-proxy-manager
    restart: always
    ports:
      - "81:81"
      - "443:443"
      - "2222:22"
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${WORDPRESS_DB_USER}
      DB_MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      DB_MYSQL_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - /mnt/docker/ppnginx-proxy-manager/data:/data
      - /mnt/docker/ppnginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-tier

networks:
  app-tier:
  db-tier:
  proxy-tier:
